post:
  operationId: createMotionAreaConfiguration
  summary: Create a new resource of this type
  description: Create a new resource of this type
  tags:
  - Motion Area Configuration
  security: &id001
  - HueApplicationKey: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            allOf:
            - $ref: ../common/ApiResponse.yaml
            - type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: ../common/ResourceIdentifier.yaml
    '401':
      $ref: ../common/error.yaml#/components/responses/Unauthorized
    '403':
      $ref: ../common/error.yaml#/components/responses/Forbidden
    '404':
      $ref: ../common/error.yaml#/components/responses/NotFound
    '405':
      $ref: ../common/error.yaml#/components/responses/MethodNotAllowed
    '406':
      $ref: ../common/error.yaml#/components/responses/NotAcceptable
    '409':
      $ref: ../common/error.yaml#/components/responses/Conflict
    '429':
      $ref: ../common/error.yaml#/components/responses/TooManyRequests
    '500':
      $ref: ../common/error.yaml#/components/responses/InternalServerError
    '503':
      $ref: ../common/error.yaml#/components/responses/ServiceUnavailable
    '507':
      $ref: ../common/error.yaml#/components/responses/InsufficientStorage
get:
  operationId: getMotionAreaConfigurations
  summary: List all resources of this type
  description: List all resources of this type
  tags:
  - Motion Area Configuration
  security: *id001
  responses:
    '200':
      description: Motion Area Configuration Success Response
      content:
        application/json:
          schema:
            allOf:
            - $ref: ../common/ApiResponse.yaml
            - type: object
              properties:
                data:
                  type: array
                  items:
                    $ref: ../common/Resource.yaml
    '401':
      $ref: ../common/error.yaml#/components/responses/Unauthorized
    '403':
      $ref: ../common/error.yaml#/components/responses/Forbidden
    '404':
      $ref: ../common/error.yaml#/components/responses/NotFound
    '405':
      $ref: ../common/error.yaml#/components/responses/MethodNotAllowed
    '406':
      $ref: ../common/error.yaml#/components/responses/NotAcceptable
    '409':
      $ref: ../common/error.yaml#/components/responses/Conflict
    '429':
      $ref: ../common/error.yaml#/components/responses/TooManyRequests
    '500':
      $ref: ../common/error.yaml#/components/responses/InternalServerError
    '503':
      $ref: ../common/error.yaml#/components/responses/ServiceUnavailable
    '507':
      $ref: ../common/error.yaml#/components/responses/InsufficientStorage
